# Test hepdata_lib
name: 'Integration tests'
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: root:latest
      uses: docker://rootproject/root:latest
      run: |
        pip install pytest
        python setup.py test