# Test hepdata_lib
name: 'Integration tests'
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: 'rootproject/root:latest'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: root:latest
      run: |
        yum install -y python-pip ghostscript
        pip install --user pytest
        python setup.py test