# Test hepdata_lib
name: 'Integration tests'
on: [push, pull_request]
description: 'Run pytest matrix for different Python versions with ROOT'
jobs:
  name: My job
  runs-on: ubuntu-latest
  steps:
  - name: Test
    run:
      - pip install pytest
      - python setup.py test