# Test hepdata_lib
name: 'Integration tests'
on: [push, pull_request]
jobs:
  test:
    container: rootproject/root:latest
    steps:
    - name: root:latest

      run: |
        pip install pytest
        python setup.py test